version: "3"

services:
  switches:
    container_name: APIServer
    image: "switches"
    networks:
      switches_network:
        ipv4_address: 172.16.1.1
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "6000:80"
      # - "6001:443"
  redis:
    container_name: redis
    image: "redis:latest"
    networks:
      switches_network:
        ipv4_address: 172.16.1.2
    ports:
      - "6379:6379"

networks:
  switches_network:
    ipam:
      driver: default
      config:
        - subnet: 172.16.0.0/16
